<!DOCTYPE TS><TS>
<context>
    <name>@default</name>
    <message>
        <source>ICON_PLOT3D_MERGE_SCALAR_BARS</source>
        <translation>plot3d_merge_scalar_bars.png</translation>
    </message>
    <message>
        <source>ICON_PLOT3D_MINUS</source>
        <translation>plot3d_minus.png</translation>
    </message>
    <message>
        <source>ICON_PLOT3D_MODE_2D</source>
        <translation>plot3d_mode_2d.png</translation>
    </message>
    <message>
        <source>ICON_PLOT3D_SURFACES_SETTINGS</source>
        <translation>plot3d_surfaces_settings.png</translation>
    </message>
</context>
</TS>
