TEMPLATE = subdirs
CONFIG += ordered

SUBDIRS  = Qtx
SUBDIRS += DDS
SUBDIRS += QDS
SUBDIRS += SUIT
SUBDIRS += SUITApp
SUBDIRS += STD
SUBDIRS += CAF
SUBDIRS += CAM
SUBDIRS += LogWindow
SUBDIRS += PyInterp
SUBDIRS += PyConsole
SUBDIRS += Prs
SUBDIRS += OBJECT
SUBDIRS += OCCViewer
SUBDIRS += Event

